server:
  port: 8888
spring:

  application:
    name: configmodel
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/
    #消息总线配置
    bus:
      enabled: true
      trace:
        enabled: true
      refresh:
        enabled: true  #开启总线消息更新功能

    consul:
      host: 172.19.79.5
      port: 8500
      discovery:
        tags: version=1.0
        #        healthCheckPath: /health
        healthCheckInterval: 5s
        instanceId: ${spring.application.name}:${spring.cloud.consul.host}:${server.port}

    # kafka测试环境
    stream:
      kafka:
        binder:
          brokers: 172.19.79.1:6667,172.19.79.2:6667,172.19.79.3:6667
management:
  endpoint:
    bus-refresh:
      enabled: true
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
