server:
  port: 8880

feign:
  hystrix:
    enabled: true

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    #消息总线配置
    bus:
      enabled: true
      trace:
        enabled: true
      refresh:
        enabled: true  #开启总线消息更新功能




management.endpoint.bus-refresh.enabled: true
management.endpoints.web.exposure.include: bus-refresh

name: "测试一下"
