server:
  port: 8880

feign:
  hystrix:
    enabled: true

spring:
  cloud:
    #消息总线配置
    bus:
      enabled: true
      trace:
        enabled: true
      refresh:
        enabled: true  #开启总线消息更新功能

    # kafka测试环境
    stream:
      kafka:
        binder:
          brokers: 172.19.79.1:6667,172.19.79.2:6667,172.19.79.3:6667

management.endpoint.bus-refresh.enabled: true
management.endpoints.web.exposure.include: info, health, loggers, logfile, configprops, bus-refresh

name: "测试一下"
