spring:
  cloud:
    gateway:
      routes:
        - id: host_route
          uri: http://localhost:8880
          predicates:
            - Path=/feign/**
          filters:
            - StripPrefix=1
        # 配置中心
        - id: host_route
          uri: http://localhost:8888
          predicates:
            - Path=/config/**
          filters:
            - StripPrefix=1

        - id: host_route
          uri: http://localhost:8081
          predicates:
            - Path=/1/**
          filters:
            - StripPrefix=1
        - id: host_route
          uri: http://localhost:8082
          predicates:
            - Path=/2/**
          filters:
            - StripPrefix=1

    # kafka测试环境
    stream:
      kafka:
        binder:
          brokers: 172.19.79.1:6667,172.19.79.2:6667,172.19.79.3:6667

server:
  port: 8080

request-modify:
  parametersMap:
    client:
      seer: fuyun2019
      testclient: fuyun2019
  modifyList:
    - routeId: baize-server
      httpMethod: POST
      paths: /oauth/token,/baize/oauth/token
      addValue:
        client_secret:
          #这里的client对应parametersMap中的client, client_id即根据已有参数获取值的key
          client: client_id
    - routeId: baize-server
      httpMethod: POST
      paths: /appcerts,/appcerts/password,/baize/appcerts,/baize/appcerts/password
      addValue:
        clientSecret:
          client: clientId